# Generated by Django 5.0 on 2023-12-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Cameroon', 'Cameroon'), ('Ethiopia', 'Ethiopia'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Uganda', 'Uganda')], max_length=50)),
                ('state', models.BooleanField()),
                ('country_code', models.CharField(max_length=5)),
                ('number', models.CharField(max_length=15)),
            ],
        ),
    ]
