# Generated by Django 5.0 on 2023-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneNumberValidations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='country',
            field=models.CharField(choices=[('Cameroon', '+237'), ('Ethiopia', '+251'), ('Morocco', '+212'), ('Mozambique', '+258'), ('Uganda', '+256')], max_length=50),
        ),
    ]
