# Generated by Django 5.0 on 2023-12-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneNumberValidations', '0002_alter_phonenumber_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='country',
            field=models.CharField(choices=[('Cameroon', 'Cameroon'), ('Ethiopia', 'Ethiopia'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Uganda', 'Uganda')], max_length=50),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='country_code',
            field=models.CharField(choices=[('+251', '+237'), ('+251', '+251'), ('+212 ', '+212 '), ('+258 ', '+258 '), ('+256', '+256 ')], max_length=5),
        ),
    ]
